### ISSUE TITLE
What is the latest development of this project? What's the problem?

### ISSUE THREAD

**Issue by Nliver** [kaiyuanshe/KToken#7]
Maybe we can discuss the difficulties with the current project~

**Comment by AmbitionCX** [comment]
Thank you, Nliver. We discussed rebuilding the system on Feishu, and the latest process will be discussed at the Kaiyuanshe infrastructure group's regular meeting.

I'll push the code to GitHub soon.

**Comment by Nliver** [comment]
> Thank you, Nliver. We discussed rebuilding the system on Feishu, and the latest process will be discussed at the Kaiyuanshe infrastructure group's regular meeting.
> 
> I'll push the code to GitHub soon.

Cool~ I look forward to the latest progress of this project~

**Comment by AmbitionCX** [comment]
The ktoken version 3 have pushed to the main branch. 
It contains:
 - onchain: an ERC20 token with transfer function disabled (finished)
 - backend: a fastify server to read and transfer tokens in the backend (essential function finished)
 - frontend: I wrote a Vue template, but we may use Reactor later, which remains unfinished.

We will discuss progress during the Kaiyuanshe infrastructure group's weekly meeting on Sundays at 20:00 (UTC+8) in Chinese. You are welcome to join us if you are interested in this project.

Thank you. I will close this issue.
